filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    enabled: true
    paths:
      - /app/logs/*.log

setup.template.name: "go-task-api"
setup.template.pattern: "go-task-api-*"
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "go-task-api-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"
