name: "task_mgt_api-filebeat-logs"
logging.metrics.enabled: false
xpack.monitoring.enabled: true
xpack.security.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /src/logs/*.log
  fields:
    service: task_mgt_api
  fields_under_root: true
  json:
    keys_under_root: true
    overwrite_keys: true
    message_key: 'message'

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "task_mgt_api-filebeat-logs-%{+yyyy.MM.dd}"