services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env 
      - ./logs:/app/logs
      - ./config:/app/config:ro
    networks:
      - app-network
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  fluentbit:
    image: fluent/fluent-bit:2.2
    volumes:
      - ./fluentbit/config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./fluentbit/config/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./logs:/app/logs:ro
    networks:
      - app-network
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - kibana_data:/usr/share/kibana/data

volumes:
  elasticsearch_data:
  kibana_data:

networks:
  app-network:
    driver: bridge