basePath: /
definitions:
  models.Priority:
    enum:
    - low
    - medium
    - high
    type: string
    x-enum-varnames:
    - PriorityLow
    - PriorityMedium
    - PriorityHigh
  models.Status:
    enum:
    - todo
    - in_progress
    - done
    type: string
    x-enum-varnames:
    - StatusTodo
    - StatusInProgress
    - StatusDone
  models.Task:
    properties:
      created_at:
        type: string
      description:
        maxLength: 100
        type: string
      due_date:
        type: string
      id:
        type: integer
      priority:
        allOf:
        - $ref: '#/definitions/models.Priority'
        enum:
        - low
        - medium
        - high
      status:
        allOf:
        - $ref: '#/definitions/models.Status'
        enum:
        - todo
        - in_progress
        - done
      title:
        maxLength: 100
        minLength: 3
        type: string
      updated_at:
        type: string
    required:
    - priority
    - status
    - title
    type: object
  pkg.SwaggerErrorResponse:
    properties:
      details:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  pkg.SwaggerSuccessResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for managing tasks and users in the system
  title: Task Management API
  version: "1.0"
paths:
  /tasks:
    post:
      consumes:
      - application/json
      description: Creates a new task and stores it in the database
      parameters:
      - description: Task details
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Task created successfully
          schema:
            $ref: '#/definitions/pkg.SwaggerSuccessResponse'
        "400":
          description: Invalid request payload or validation error
          schema:
            $ref: '#/definitions/pkg.SwaggerErrorResponse'
        "500":
          description: Failed to create task
          schema:
            $ref: '#/definitions/pkg.SwaggerErrorResponse'
      summary: Create a new task
      tags:
      - tasks
swagger: "2.0"
